### ISSUE TITLE
error when running the Starter code with GPU

### ISSUE THREAD

**Issue by pandababyer** [facebookresearch/grounded-video-description#29]
Hello, Luowei, thanks for your code ,its is quit helpful ! When I download all the dataset, configure the conda environment and I have this problem when I running the starter code with cuda able:

428 classes have the associated lemma word!
Traceback (most recent call last):
  File "main.py", line 697, in <module>
    lang_stats = eval(epoch, opt)
  File "main.py", line 358, in eval
    input_ppls, dummy, dummy, ppls_feat, dummy, sample_idx, pnt_mask, 'sample', eval_opt)
  File "/home/xddz/anaconda3/envs/gvd_pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/big_data/pgc/code/grounded-video-description/misc/model.py", line 233, in forward
    seq, seqLogprobs, att2, sim_mat = self._sample(segs_feat, ppls, num, ppls_feat, sample_idx, pnt_mask, eval_opt)
  File "/big_data/pgc/code/grounded-video-description/misc/model.py", line 510, in _sample
    F.layer_norm(self.seg_info_embed(num[:, 3:7].float()), [self.seg_info_size])), dim=-1)
  File "/home/xddz/anaconda3/envs/gvd_pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xddz/anaconda3/envs/gvd_pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/xddz/anaconda3/envs/gvd_pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xddz/anaconda3/envs/gvd_pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 92, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/xddz/anaconda3/envs/gvd_pytorch1.1/lib/python3.7/site-packages/torch/nn/functional.py", line 1406, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/THCBlas.cu:259

When I run the cod without GPU, it works well. so it really confuse me.  My gpu is 2080ti and cuda version is 10.1.Looking forward to your reply, thanks!

**Comment by pandababyer** [comment]
i solve it  :)

**Comment by yuanzheng625** [comment]
> i solve it :)

may I know how you solve this issue?
